name: "Traefik (Beta)"
version: "0.5.3"
slug: "traefik-beta"
description: "Reverse Proxy for Web Services"
arch: ["armv7", "aarch64", "amd64"]
startup: "system"
stage: stable
boot: "auto"
image: "pheelee/hassio-addon-traefik-{arch}"
ports:
    "80/tcp": 80
    "443/tcp": 443
hassio_api: false
hassio_role: "default"
map: []
options:
    loglevel: "error"
    email: ""
    authEndpoint: ""
    cookieSecret: "your-super-secure-string-here"
    insecureSkipVerify: false
    environment: []
    hosts: []
    rootCAs: []
    ingress: true
    panel_icon: "mdi:routes"
schema:
    loglevel: "list(debug|panic|fatal|error|warn|info)"
    email: "email"
    authEndpoint: "str?"
    cookieSecret: "str?"
    insecureSkipVerify: "bool"
    environment: ["str?"]
    hosts: ["str?"]
    rootCAs: ["str?"]
